[project]
name = "ndice"
version = "0.1.0-rc.1"
description = "夜骰基础掷骰指令规则包"
authors = [
    {name = "苏向夜",email = "fu050409@163.com"},
]
license = "AGPLv3"
readme = "README.md"

[requirements]

[dependencies]
diceutils = "*"
