[project]
name = "noctisdice"
version = "0.1.0"
description = "夜骰核心组件"
authors = [
    {name = "fu050409",email = "fu050409@163.com"},
]
dependencies = [
    "infini>2.1.0",
    "psutil>=5.9.8",
    "diceutils>=0.3.6",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "AGPLv3"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "pytest",
    "ipdm>=0.2.0-beta",
]
