[project]
name = "noctisdice"
version = "0.1.0"
description = "夜骰核心组件"
authors = [
    {name = "fu050409",email = "fu050409@163.com"},
]
license = "AGPLv3"
readme = "README.md"

[requirements]
noctisdice = "4.0.0-rc.4"
coc = "0.1.0-rc.1"
ndice = "0.1.0-rc.1"

[dependencies]
diceutils = "*"
